# Generated by Django 4.2 on 2023-12-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_purchase_price_purchase_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
